mqtt:
  enabled: false

detectors:
  rknn:
    type: rknn
    num_cores: 0

ffmpeg:
  hwaccel_args: preset-rkmpp

go2rtc:
  streams: {}

detect:
  enabled: true
  fps: 5
  min_initialized: 2
  max_disappeared: 25
  stationary:
    classifier: true
    interval: 50
    threshold: 50

record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  continuous:
    days: 0
  motion:
    days: 0
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 7
      mode: active_objects
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 3
      mode: active_objects

objects:
  track:
    - person
    - car

snapshots:
  enabled: true
  bounding_box: true

cameras: {}

version: 0.17-0